# Generated by Django 4.2.2 on 2023-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='output_format',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
