# Generated by Django 4.2.2 on 2023-06-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_video_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
